services:
  - type: web
    name: shopify-order-tracker
    env: node
    buildCommand: npm install && ./node_modules/.bin/remix build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SHOPIFY_AUTH_CALLBACK_URL
        sync: false
      - key: SHOPIFY_APP_SCOPES
        value: "write_products,write_orders,read_orders" 